{{- if include "endoriumfort.renderSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "endoriumfort.fullname" . }}
  labels:
    {{- include "endoriumfort.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets.vaultKey }}
  ENDORIUMFORT_VAULT_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.license }}
  ENDORIUMFORT_LICENSE: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.relayEnrollSecret }}
  ENDORIUMFORT_RELAY_ENROLL_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.clusterSharedSecret }}
  ENDORIUMFORT_CLUSTER_SHARED_SECRET: {{ . | quote }}
  {{- end }}
{{- end }}
