apiVersion: v1
kind: Service
metadata:
  name: {{ include "endoriumfort.fullname" . }}
  labels:
    {{- include "endoriumfort.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "endoriumfort.selectorLabels" . | nindent 4 }}
